const componentLabels: Record<string, string> = {
  PageContainer: '页面容器',
  Section: '区块',
  Card: '卡片',
  Button: '按钮',
  Input: '输入框',
  Select: '选择器',
  SearchBar: '搜索区',
  Table: '表格',
  Form: '表单',
  Modal: '弹窗',
  Drawer: '抽屉',
  Tabs: '标签页',
  Message: '消息提示',
  FloatButton: '悬浮按钮',
  'FloatButton.Group': '悬浮按钮组',
  'FloatButton.BackTop': '返回顶部',
  H1: 'H1',
  H2: 'H2',
  H3: 'H3',
  BodyText: 'body text',
  HelperText: 'helper text',
  LinkText: 'link text',
  ErrorText: 'error text',
  Annotation: 'annotation',
  StickyNote: 'sticky note',
  Rectangle: 'rectangle',
  Circle: 'circle',
  Line: 'line',
  Arrow: 'arrow',
  ImageWidget: 'image',
  IconWidget: 'icon',
  Placeholder: 'placeholder',
  DividerWidget: 'divider',
  HotZone: 'hot zone',
  ModuleTitle: 'module title',
  PageTitle: 'page title',
  StatusLabel: 'status text',
  AmountText: 'amount text',
  NumericText: 'numeric text',
  TimeText: 'time text',
};

export function componentLabel(type: string): string {
  return componentLabels[type] ?? type;
}
