const componentLabels: Record<string, string> = {
  PageContainer: '页面容器',
  Section: '区块',
  Card: '卡片',
  Button: '按钮',
  Input: '输入框',
  Select: '选择器',
  SearchBar: '搜索区',
  Table: '表格',
  Form: '表单',
  Modal: '弹窗',
  Drawer: '抽屉',
  Tabs: '标签页',
  Message: '消息提示',
  Image: '图片',
  FloatButton: '悬浮按钮',
  'FloatButton.Group': '悬浮按钮组',
  'FloatButton.BackTop': '返回顶部',
  H1: '一级标题',
  H2: '二级标题',
  H3: '三级标题',
  BodyText: '正文',
  HelperText: '辅助说明',
  LinkText: '链接文本',
  ErrorText: '错误提示',
  Annotation: '批注',
  StickyNote: '便签',
  Rectangle: '矩形',
  Circle: '圆形',
  Line: '线条',
  Arrow: '箭头',
  ImageWidget: '图片元件',
  IconWidget: '图标元件',
  Placeholder: '占位框',
  DividerWidget: '分割线',
  HotZone: '热区',
  ModuleTitle: '模块标题',
  PageTitle: '页面标题',
  StatusLabel: '状态标签',
  AmountText: '金额文本',
  NumericText: '数字文本',
  TimeText: '时间文本',
  'pro.ProLayout': 'Pro 布局',
  'pro.PageContainer': 'Pro 页面容器',
  'pro.ProTable': 'Pro 表格',
  'pro.EditableProTable': '可编辑 Pro 表格',
  'pro.ProForm': 'Pro 表单',
  'pro.ProCard': 'Pro 卡片',
  'pro.ProDescriptions': 'Pro 描述列表',
  'pro.ProList': 'Pro 列表',
};

export function componentLabel(type: string): string {
  return componentLabels[type] ?? type;
}
