import type { ComponentApiProp, ComponentApiSchema } from '../types/apiSchema';

const option = (label: string, value: string) => ({ label, value });

const commonProps: ComponentApiProp[] = [
  {
    name: 'icon',
    labelZh: '图标',
    description: '自定义图标',
    typeText: 'ReactNode',
    valueKind: 'reactNode',
    editor: 'icon',
    group: '内容',
    path: 'props.icon',
    editable: true,
  },
  {
    name: 'content',
    labelZh: '按钮内容',
    description: '文字及其它内容，方形按钮更适合展示内容',
    typeText: 'ReactNode',
    valueKind: 'reactNode',
    editor: 'reactNode',
    group: '内容',
    path: 'props.content',
    visibleWhen: { path: 'props.shape', operator: 'equals', value: 'square' },
    editable: true,
  },
  {
    name: 'tooltip',
    labelZh: '提示文字',
    description: '气泡提示内容',
    typeText: 'ReactNode | TooltipProps',
    valueKind: 'object',
    editor: 'reactNode',
    group: '内容',
    path: 'props.tooltip',
    editable: true,
  },
  {
    name: 'type',
    labelZh: '按钮类型',
    description: '设置按钮类型',
    typeText: 'default | primary',
    valueKind: 'enum',
    editor: 'select',
    options: [option('默认', 'default'), option('主按钮', 'primary')],
    group: '基础',
    path: 'props.type',
    defaultValue: 'default',
    editable: true,
  },
  {
    name: 'shape',
    labelZh: '按钮形状',
    description: '设置按钮形状',
    typeText: 'circle | square',
    valueKind: 'enum',
    editor: 'select',
    options: [option('圆形', 'circle'), option('方形', 'square')],
    group: '基础',
    path: 'props.shape',
    defaultValue: 'circle',
    editable: true,
  },
  {
    name: 'href',
    labelZh: '跳转地址',
    description: '点击跳转的地址',
    typeText: 'string',
    valueKind: 'string',
    editor: 'text',
    group: '行为',
    path: 'props.href',
    editable: true,
  },
  {
    name: 'target',
    labelZh: '打开方式',
    description: 'href 存在时生效',
    typeText: 'string',
    valueKind: 'enum',
    editor: 'select',
    options: [option('当前窗口', '_self'), option('新窗口', '_blank')],
    group: '行为',
    path: 'props.target',
    visibleWhen: { path: 'props.href', operator: 'exists' },
    editable: true,
  },
  {
    name: 'badge',
    labelZh: '徽标',
    description: '带徽标数字的悬浮按钮',
    typeText: 'BadgeProps',
    valueKind: 'object',
    editor: 'objectEditor',
    group: '内容',
    path: 'props.badge',
    editable: true,
  },
  {
    name: 'htmlType',
    labelZh: 'htmlType',
    description: '设置原生按钮类型',
    typeText: 'button | submit | reset',
    valueKind: 'enum',
    editor: 'select',
    options: [option('button', 'button'), option('submit', 'submit'), option('reset', 'reset')],
    group: '基础',
    path: 'props.htmlType',
    defaultValue: 'button',
    editable: true,
    advanced: true,
  },
  {
    name: 'classNames',
    labelZh: 'classNames',
    description: '语义化结构样式类名，高级配置',
    typeText: 'Record<string, string>',
    valueKind: 'semanticClass',
    editor: 'classNameEditor',
    group: '高级',
    path: 'props.classNames',
    editable: true,
    advanced: true,
  },
  {
    name: 'onClick',
    labelZh: '点击后执行',
    description: '点击按钮时执行的交互',
    typeText: '(event) => void',
    valueKind: 'function',
    editor: 'interactionEvent',
    group: '事件',
    path: 'events.onClick',
    editable: true,
  },
];

const groupProps: ComponentApiProp[] = [
  ...commonProps.filter((prop) => ['shape', 'onClick'].includes(prop.name)),
  {
    name: 'trigger',
    labelZh: '触发方式',
    description: '触发菜单展开或收起的方式',
    typeText: 'click | hover',
    valueKind: 'enum',
    editor: 'select',
    options: [option('点击', 'click'), option('悬停', 'hover')],
    group: '行为',
    path: 'props.trigger',
    defaultValue: 'click',
    editable: true,
  },
  {
    name: 'open',
    labelZh: '是否展开',
    description: '受控展开，需配合 trigger 使用',
    typeText: 'boolean',
    valueKind: 'boolean',
    editor: 'switch',
    group: '行为',
    path: 'props.open',
    visibleWhen: { path: 'props.trigger', operator: 'exists' },
    editable: true,
  },
  {
    name: 'placement',
    labelZh: '弹出位置',
    description: '自定义菜单弹出位置',
    typeText: 'top | left | right | bottom',
    valueKind: 'enum',
    editor: 'select',
    options: [option('上', 'top'), option('左', 'left'), option('右', 'right'), option('下', 'bottom')],
    group: '基础',
    path: 'props.placement',
    defaultValue: 'top',
    editable: true,
  },
  {
    name: 'closeIcon',
    labelZh: '关闭图标',
    description: '自定义关闭图标',
    typeText: 'ReactNode',
    valueKind: 'reactNode',
    editor: 'icon',
    group: '内容',
    path: 'props.closeIcon',
    editable: true,
  },
  {
    name: 'items',
    labelZh: '子按钮列表',
    description: '按钮组内的悬浮按钮',
    typeText: 'FloatButton[]',
    valueKind: 'array',
    editor: 'arrayEditor',
    group: '内容',
    path: 'props.items',
    editable: true,
  },
  {
    name: 'onOpenChange',
    labelZh: '展开变化后执行',
    description: '展开或收起时执行的交互',
    typeText: '(open: boolean) => void',
    valueKind: 'function',
    editor: 'interactionEvent',
    group: '事件',
    path: 'events.onOpenChange',
    editable: true,
  },
];

const backTopProps: ComponentApiProp[] = [
  {
    name: 'duration',
    labelZh: '返回顶部耗时',
    description: '回到顶部所需时间，单位 ms',
    typeText: 'number',
    valueKind: 'number',
    editor: 'number',
    group: '基础',
    path: 'props.duration',
    defaultValue: '450',
    editable: true,
  },
  {
    name: 'target',
    labelZh: '监听目标元素',
    description: '滚动监听目标，普通配置默认使用 window',
    typeText: '() => HTMLElement',
    valueKind: 'unknown',
    editor: 'advancedJson',
    group: '高级',
    path: 'props.target',
    defaultValue: 'window',
    editable: true,
    advanced: true,
  },
  {
    name: 'visibilityHeight',
    labelZh: '显示所需滚动高度',
    description: '滚动高度达到该值后显示返回顶部按钮',
    typeText: 'number',
    valueKind: 'number',
    editor: 'number',
    group: '基础',
    path: 'props.visibilityHeight',
    defaultValue: '400',
    editable: true,
  },
  {
    name: 'onClick',
    labelZh: '点击后执行',
    description: '点击按钮后的交互',
    typeText: '() => void',
    valueKind: 'function',
    editor: 'interactionEvent',
    group: '事件',
    path: 'events.onClick',
    editable: true,
  },
];

export const floatButtonApiSchema: ComponentApiSchema = {
  source: 'official-docs',
  sourceUrl: 'https://ant.design/components/float-button/',
  componentVersion: 'antd@6',
  sections: [
    { key: 'common', title: '共同 API', componentVariant: 'FloatButton', props: commonProps },
    { key: 'group', title: 'FloatButton.Group', componentVariant: 'FloatButton.Group', props: groupProps },
    { key: 'backTop', title: 'FloatButton.BackTop', componentVariant: 'FloatButton.BackTop', props: backTopProps },
  ],
};
