import type { ComponentApiProp, ComponentApiSchema } from '../types/apiSchema';

const option = (label: string, value: string | number | boolean) => ({ label, value });

const props: ComponentApiProp[] = [
  {
    name: 'children',
    labelZh: '内容',
    description: '折叠面板中的主要内容。项目会把它本地化映射为标题与内容区域。',
    typeText: 'ReactNode',
    valueKind: 'reactNode',
    editor: 'reactNode',
    group: '内容',
    path: 'props.children',
    editable: true,
  },
  {
    name: 'classes',
    labelZh: '样式类',
    description: '覆盖或扩展组件内部状态与结构类名，例如 root、expanded、disabled、gutters、rounded、region。',
    typeText: 'object',
    valueKind: 'semanticClass',
    editor: 'classNameEditor',
    group: '样式',
    path: 'props.classes',
    editable: true,
    advanced: true,
  },
  {
    name: 'defaultExpanded',
    labelZh: '默认展开',
    description: '非受控模式下，页面首次渲染时是否默认展开。',
    typeText: 'bool',
    defaultValue: 'false',
    valueKind: 'boolean',
    editor: 'switch',
    group: '行为',
    path: 'props.defaultExpanded',
    editable: true,
  },
  {
    name: 'disabled',
    labelZh: '禁用',
    description: '禁用后用户不能展开或收起面板。',
    typeText: 'bool',
    defaultValue: 'false',
    valueKind: 'boolean',
    editor: 'switch',
    group: '行为',
    path: 'props.disabled',
    editable: true,
  },
  {
    name: 'disableGutters',
    labelZh: '禁用内边距',
    description: '移除标题区域默认左右内边距，用于更紧凑的后台信息面板。',
    typeText: 'bool',
    defaultValue: 'false',
    valueKind: 'boolean',
    editor: 'switch',
    group: '样式',
    path: 'props.disableGutters',
    editable: true,
  },
  {
    name: 'expanded',
    labelZh: '展开状态',
    description: '受控模式下指定是否展开。未设置时使用默认展开状态。',
    typeText: 'bool',
    valueKind: 'boolean',
    editor: 'switch',
    group: '行为',
    path: 'props.expanded',
    editable: true,
  },
  {
    name: 'onChange',
    labelZh: '切换后执行',
    description: '用户展开或收起时触发，可绑定页面跳转、显示提示、状态更新等交互。',
    typeText: 'function(event: React.SyntheticEvent, expanded: boolean) => void',
    valueKind: 'function',
    editor: 'interactionEvent',
    group: '事件',
    path: 'events.onChange',
    editable: true,
  },
  {
    name: 'slotProps',
    labelZh: '插槽属性',
    description: '为 root、heading、transition、region 等插槽传入属性。',
    typeText: '{ heading?: object, region?: object, root?: object, transition?: object }',
    valueKind: 'object',
    editor: 'objectEditor',
    group: '高级',
    path: 'props.slotProps',
    editable: true,
    advanced: true,
  },
  {
    name: 'slots',
    labelZh: '插槽组件',
    description: '替换 root、heading、transition、region 插槽使用的组件。',
    typeText: '{ heading?: elementType, region?: elementType, root?: elementType, transition?: elementType }',
    valueKind: 'object',
    editor: 'objectEditor',
    group: '高级',
    path: 'props.slots',
    editable: true,
    advanced: true,
  },
  {
    name: 'sx',
    labelZh: '样式扩展',
    description: 'MUI sx 样式扩展对象。项目中作为高级样式配置保存，渲染时优先使用基础样式字段。',
    typeText: 'Array<func | object | bool> | func | object',
    valueKind: 'css',
    editor: 'styleEditor',
    group: '样式',
    path: 'props.sx',
    editable: true,
    advanced: true,
  },
  {
    name: 'component',
    labelZh: '根元素',
    description: 'Paper 继承属性：设置根节点使用的元素或组件。',
    typeText: 'elementType',
    valueKind: 'string',
    editor: 'text',
    group: '高级',
    path: 'props.component',
    editable: true,
    advanced: true,
  },
  {
    name: 'elevation',
    labelZh: '阴影层级',
    description: 'Paper 继承属性：阴影深度，适用于 elevation 变体。',
    typeText: 'integer',
    defaultValue: '1',
    valueKind: 'number',
    editor: 'number',
    group: '样式',
    path: 'props.elevation',
    editable: true,
  },
  {
    name: 'square',
    labelZh: '直角边框',
    description: 'Paper 继承属性：为 true 时取消圆角。',
    typeText: 'bool',
    defaultValue: 'false',
    valueKind: 'boolean',
    editor: 'switch',
    group: '样式',
    path: 'props.square',
    editable: true,
  },
  {
    name: 'variant',
    labelZh: '外观变体',
    description: 'Paper 继承属性：使用阴影或描边风格。',
    typeText: 'elevation | outlined | string',
    defaultValue: 'elevation',
    valueKind: 'enum',
    editor: 'select',
    options: [option('阴影', 'elevation'), option('描边', 'outlined')],
    group: '样式',
    path: 'props.variant',
    editable: true,
  },
  {
    name: 'TransitionComponent',
    labelZh: '过渡组件（旧版）',
    description: '已废弃：请改用 slots.transition。',
    typeText: 'elementType',
    valueKind: 'string',
    editor: 'text',
    group: '高级',
    path: 'props.TransitionComponent',
    deprecated: true,
    deprecatedReason: 'MUI 建议改用 slots.transition。',
    editable: true,
    advanced: true,
  },
  {
    name: 'TransitionProps',
    labelZh: '过渡属性（旧版）',
    description: '已废弃：请改用 slotProps.transition。',
    typeText: 'object',
    valueKind: 'object',
    editor: 'objectEditor',
    group: '高级',
    path: 'props.TransitionProps',
    deprecated: true,
    deprecatedReason: 'MUI 建议改用 slotProps.transition。',
    editable: true,
    advanced: true,
  },
];

export const muiAccordionApiSchema: ComponentApiSchema = {
  source: 'official-docs',
  sourceUrl: 'https://mui.com/material-ui/api/accordion/',
  docsVersion: '2026-05-11',
  componentVersion: 'MUI Material UI Accordion API',
  sections: [
    {
      key: 'accordion',
      title: 'Accordion API',
      componentVariant: 'Accordion',
      description: '完整复用 MUI Accordion API，并在本地以中文手风琴组件展示。',
      props,
    },
  ],
};
